import type { AsciiPreset } from '../../core/types';

export const compositingPreset: AsciiPreset = {
  id: 'compositing',
  name: 'Compositing Demo',
  glyphSet: [' ', '.', ':', '-', '=', '+', '*', '#', '@'],
  motionField: 'wave',
  plugins: [
    { id: 'wave', type: 'effect' },
    { id: 'trails', type: 'effect' },
    { id: 'radialSymmetry', type: 'pattern' },
    { id: 'spiral', type: 'pattern' },
  ],
  patterns: ['radialSymmetry', 'spiral'],
  motions: [{ id: 'flowField', weight: 0.6 }],
  layers: [
    {
      id: 'base',
      name: 'Base Pattern',
      enabled: true,
      opacity: 1,
      blendMode: 'normal',
      pattern: 'radialSymmetry',
      mask: { type: 'radial', amount: 1, centerX: 0.5, centerY: 0.5 },
    },
    {
      id: 'overlay',
      name: 'Spiral Overlay',
      enabled: true,
      opacity: 0.65,
      blendMode: 'add',
      pattern: 'spiral',
      mask: { type: 'linear', amount: 0.8, angle: 45 },
    },
    {
      id: 'accent',
      name: 'Noise Accent',
      enabled: true,
      opacity: 0.35,
      blendMode: 'screen',
      fill: 0.6,
      mask: { type: 'noise', amount: 1.2 },
    },
  ],
  postProcessing: [
    { id: 'feedback', enabled: true, amount: 0.75 },
    { id: 'smear', enabled: true, amount: 0.35 },
  ],
  controls: [
    {
      name: 'density',
      label: 'Density',
      min: 0.3,
      max: 2,
      default: 1,
      step: 0.1,
    },
    {
      name: 'speed',
      label: 'Speed',
      min: 0.1,
      max: 3,
      default: 0.8,
      step: 0.1,
    },
    {
      name: 'trailAmount',
      label: 'Trails',
      min: 0,
      max: 1,
      default: 0.4,
      step: 0.05,
    },
    {
      name: 'symmetry',
      label: 'Symmetry',
      min: 2,
      max: 12,
      default: 8,
      step: 1,
    },
    {
      name: 'spiralAmount',
      label: 'Spiral',
      min: 0,
      max: 1,
      default: 0.7,
      step: 0.05,
    },
    {
      name: 'postFeedback',
      label: 'Feedback',
      min: 0,
      max: 1,
      default: 0.75,
      step: 0.05,
    },
    {
      name: 'postSmear',
      label: 'Smear',
      min: 0,
      max: 1,
      default: 0.35,
      step: 0.05,
    },
  ],
  density: 1,
  speed: 0.8,
  trailAmount: 0.4,
  glitchAmount: 0.05,
  symmetry: 8,
  spiralAmount: 0.7,
  postFeedback: 0.75,
  postSmear: 0.35,
};
