/**
 * Plantasonic Design System — Official code generators.
 *
 * Scaffolds that follow Design System conventions automatically: token-driven,
 * framework-agnostic HTML-string render functions, accessible markup, and a
 * matching metadata record so generated elements register themselves.
 *
 * Each generator returns {@link GeneratedFile}s (path + content) so callers
 * (CLI, build tools, AI agents) can write them wherever appropriate.
 */
import type { ShellVariant } from '../shell/types.ts';

export interface GeneratedFile {
  path: string;
  content: string;
  description?: string;
}

function pascal(name: string): string {
  return name
    .replace(/[-_\s]+/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
}

function camel(name: string): string {
  const p = pascal(name);
  return p.charAt(0).toLowerCase() + p.slice(1);
}

function kebab(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[\s_]+/g, '-')
    .toLowerCase();
}

export interface GenerateComponentOptions {
  name: string;
  purpose?: string;
  category?: string;
  variants?: string[];
}

/** Generate a token-driven component render function + metadata record. */
export function generateComponent(options: GenerateComponentOptions): GeneratedFile[] {
  const fn = camel(options.name);
  const Name = pascal(options.name);
  const cls = `ds-c-${kebab(options.name)}`;
  const category = options.category ?? 'controls';
  const variants = options.variants ?? [];
  const variantType = variants.length ? variants.map((v) => `'${v}'`).join(' | ') : 'string';

  const component = `/**
 * ${Name} — generated by plantasonic-design-system generateComponent().
 * Token-driven, framework-agnostic HTML string. No hardcoded values.
 */
import { classList, escapeHtml, type Size } from './types.ts';

export type ${Name}Variant = ${variantType};

export type ${Name}Options = {
  label: string;
  variant?: ${Name}Variant;
  size?: Size;
  id?: string;
  class?: string;
};

export function ${fn}(options: ${Name}Options): string {
  const variant = options.variant${variants.length ? ` ?? '${variants[0]}'` : ''};
  const cls = classList(
    '${cls}',
    variant && \`${cls}--\${variant}\`,
    options.size && options.size !== 'md' && \`${cls}--\${options.size}\`,
    options.class,
  );
  const idAttr = options.id ? \` id="\${escapeHtml(options.id)}"\` : '';
  return \`<div class="\${cls}"\${idAttr}>\${escapeHtml(options.label)}</div>\`;
}
`;

  const metadata = `import { defineComponent } from 'plantasonic-design-system/ai';

export const ${fn}Metadata = defineComponent({
  id: 'component.${fn}',
  name: '${Name}',
  kind: 'component',
  export: '${fn}',
  version: '0.1.0',
  purpose: ${JSON.stringify(options.purpose ?? `${Name} component.`)},
  category: '${category}',
  status: 'experimental',
  source: 'plantasonic-design-system/components',
  supportedThemes: ['dark', 'light'],
  variants: ${JSON.stringify(variants)},
  props: [
    { name: 'label', type: 'string', required: true },
    { name: 'variant', type: '${Name}Variant' },
    { name: 'size', type: "'sm' | 'md' | 'lg'", default: 'md' },
  ],
  accessibility: { notes: 'Review roles/ARIA before promoting to stable.' },
  supportedLayouts: ['*'],
});
`;

  return [
    { path: `src/components/${kebab(options.name)}.ts`, content: component, description: 'Component render function' },
    { path: `src/ai/contrib/${kebab(options.name)}.meta.ts`, content: metadata, description: 'Component metadata record' },
  ];
}

export interface GenerateLayoutOptions {
  name: string;
  purpose?: string;
  variant?: ShellVariant;
  regions: string[];
}

/** Generate a layout metadata record describing regions and slots. */
export function generateLayout(options: GenerateLayoutOptions): GeneratedFile[] {
  const id = `layout.${kebab(options.name)}`;
  const regions = options.regions.map(
    (r) => `    { name: '${kebab(r)}', description: '${pascal(r)} region.' }`,
  );
  const content = `import { defineLayout } from 'plantasonic-design-system/ai';

export const ${camel(options.name)}Layout = defineLayout({
  id: '${id}',
  name: '${pascal(options.name)}',
  kind: 'layout',
  variant: '${options.variant ?? 'standard'}',
  version: '0.1.0',
  purpose: ${JSON.stringify(options.purpose ?? `${pascal(options.name)} layout.`)},
  category: 'application',
  status: 'experimental',
  source: 'plantasonic-design-system/shell',
  supportedThemes: ['dark', 'light'],
  regions: [
${regions.join(',\n')},
  ],
  supportedComponents: ['*'],
});
`;
  return [{ path: `src/ai/contrib/${kebab(options.name)}.layout.ts`, content, description: 'Layout metadata record' }];
}

export interface GeneratePatternOptions {
  name: string;
  purpose?: string;
  composedOf?: string[];
  layouts?: string[];
}

/** Generate a pattern render scaffold + metadata record. */
export function generatePattern(options: GeneratePatternOptions): GeneratedFile[] {
  const fn = camel(options.name);
  const Name = pascal(options.name);
  const meta = `import { definePattern } from 'plantasonic-design-system/ai';

export const ${fn}Pattern = definePattern({
  id: 'pattern.${kebab(options.name)}',
  name: '${Name}',
  kind: 'pattern',
  version: '0.1.0',
  purpose: ${JSON.stringify(options.purpose ?? `${Name} pattern.`)},
  category: 'application',
  status: 'experimental',
  source: 'plantasonic-design-system/ai',
  supportedThemes: ['dark', 'light'],
  api: 'render${Name}(options)',
  composedOf: ${JSON.stringify(options.composedOf ?? [])},
  supportedLayouts: ${JSON.stringify(options.layouts ?? ['*'])},
});
`;
  const render = `import { stack } from 'plantasonic-design-system/primitives';

export type ${Name}Options = { content?: string };

/** ${Name} product pattern — compose Design System components here. */
export function render${Name}(options: ${Name}Options = {}): string {
  return stack({ gap: '4', content: options.content ?? '' });
}
`;
  return [
    { path: `src/patterns/${kebab(options.name)}.ts`, content: render, description: 'Pattern render function' },
    { path: `src/ai/contrib/${kebab(options.name)}.pattern.ts`, content: meta, description: 'Pattern metadata record' },
  ];
}

export interface GenerateThemeOptions {
  name: string;
  /** Token path → value overrides (e.g. { 'color.primary.default': '#ff0066' }). */
  overrides?: Record<string, string>;
}

/** Generate a theme token override file (W3C Design Tokens JSON shape). */
export function generateTheme(options: GenerateThemeOptions): GeneratedFile[] {
  const name = kebab(options.name);
  const tokens: Record<string, unknown> = {};
  for (const [path, value] of Object.entries(options.overrides ?? {})) {
    const parts = path.split('.');
    let node: Record<string, unknown> = tokens;
    parts.forEach((part, i) => {
      if (i === parts.length - 1) {
        node[part] = { $value: value };
      } else {
        node[part] = (node[part] as Record<string, unknown>) ?? {};
        node = node[part] as Record<string, unknown>;
      }
    });
  }
  const content = JSON.stringify({ $description: `${options.name} theme overrides`, ...tokens }, null, 2) + '\n';
  return [
    {
      path: `tokens/theme.${name}.tokens.json`,
      content,
      description: 'Theme token overrides — run npm run tokens:build-css after adding to the pipeline.',
    },
  ];
}

export interface GenerateWorkspaceOptions {
  id: string;
  label?: string;
}

/** Generate a workspace registration snippet for the createApplication() SDK. */
export function generateWorkspace(options: GenerateWorkspaceOptions): GeneratedFile[] {
  const content = `import { renderCanvasMount } from 'plantasonic-design-system/instrument';

export const ${camel(options.id)}Workspace = {
  id: '${kebab(options.id)}',
  label: ${JSON.stringify(options.label ?? pascal(options.id))},
  render: () => renderCanvasMount(),
};
`;
  return [{ path: `src/workspaces/${kebab(options.id)}.ts`, content, description: 'Workspace definition' }];
}

export interface GenerateApplicationOptions {
  title: string;
  variant?: ShellVariant;
}

/** Generate a createApplication() bootstrap entrypoint. */
export function generateApplication(options: GenerateApplicationOptions): GeneratedFile[] {
  const content = `import { createApplication } from 'plantasonic-design-system/app';
import { renderCanvasMount, METRIC_PRESETS } from 'plantasonic-design-system/instrument';
import 'plantasonic-design-system/css/variables.css';

const app = createApplication({
  title: ${JSON.stringify(options.title)},
  variant: '${options.variant ?? 'instrument'}',
});

app
  .registerWorkspace({ id: 'main', render: () => renderCanvasMount() })
  .registerStatus([METRIC_PRESETS.fps(() => 60)]);

const root = document.getElementById('root');
if (root) await app.mount(root);

export { app };
`;
  return [{ path: 'src/main.ts', content, description: 'Application bootstrap' }];
}

export interface GeneratePluginOptions {
  name: string;
  description?: string;
}

/** Generate a Design System plugin scaffold. */
export function generatePlugin(options: GeneratePluginOptions): GeneratedFile[] {
  const content = `import { definePlugin } from 'plantasonic-design-system/ai';

export default definePlugin({
  name: '${kebab(options.name)}',
  version: '0.1.0',
  description: ${JSON.stringify(options.description ?? `${options.name} plugin`)},
  contributes: {
    components: [],
    layouts: [],
    patterns: [],
    themes: [],
    tokens: [],
    commands: [],
    documentation: [],
    ai: [],
  },
});
`;
  return [{ path: `plugins/${kebab(options.name)}/index.ts`, content, description: 'Plugin entrypoint' }];
}
