import type { PresetBundle } from '@plantasonic/platform-types';

/** Signal 9 broadcast preset bundles — cyberpunk resistance sessions */
export const {{APP_CONST}}_BROADCAST_BUNDLE: PresetBundle = {
  id: 'broadcast',
  name: 'Broadcast',
  description: 'Baseline resistance carrier — radio static boot sequence on the CRT grid.',
  category: 'broadcast',
  tags: ['signal-9', 'broadcast', 'starter', 'crt', 'mood:transmission-boot', 'accent:#00ff9f'],
  sound: { presetId: 'ambient' },
  visual: { presetId: 'ambient' },
  audioReactive: {
    enabled: true,
    sensitivity: 0.65,
    smoothing: 0.6,
    mappings: [
      { feature: 'bass', target: 'density', amount: 0.45, enabled: true },
      { feature: 'mids', target: 'motion', amount: 0.5, enabled: true },
      { feature: 'highs', target: 'brightness', amount: 0.4, enabled: true },
      { feature: 'amplitude', target: 'scale', amount: 0.4, enabled: true },
      { feature: 'transient', target: 'glitch', amount: 0.25, enabled: true },
    ],
  },
  workspace: {
    regions: { inspector: { visible: false } },
    activeInspectorPanel: 'audio-reactive',
  },
  ui: {
    audioReactiveEnabled: true,
    tempo: {{DEFAULT_TEMPO}},
    soundParameters: { growth: 0.35, bloom: 0.25, roots: 0.3, mold: 0.45, bacteria: 0.4 },
    visualParameters: { density: 0.65, speed: 0.45, glitchAmount: 0.15, trailAmount: 0.25 },
    bridgeSensitivity: 0.65,
    bridgeSmoothing: 0.6,
  },
};

export const {{APP_CONST}}_PRESET_BUNDLES: PresetBundle[] = [
  {{APP_CONST}}_BROADCAST_BUNDLE,
  {
    id: 'interference',
    name: 'Interference',
    description: 'Corrupted transmission static — CRT noise and scanline glitch bursts.',
    category: 'broadcast',
    tags: ['signal-9', 'interference', 'static', 'crt', 'mood:static-disruption', 'accent:#66eeff'],
    sound: { presetId: 'mold' },
    visual: { presetId: 'mold' },
    audioReactive: {
      enabled: true,
      sensitivity: 0.9,
      smoothing: 0.35,
      mappings: [
        { feature: 'bass', target: 'density', amount: 0.5, enabled: true },
        { feature: 'mids', target: 'motion', amount: 0.4, enabled: true },
        { feature: 'highs', target: 'brightness', amount: 0.6, enabled: true },
        { feature: 'amplitude', target: 'scale', amount: 0.35, enabled: true },
        { feature: 'transient', target: 'glitch', amount: 0.8, enabled: true },
      ],
    },
    workspace: { activeInspectorPanel: 'visual-parameters' },
    ui: {
      audioReactiveEnabled: true,
      tempo: 104,
      soundParameters: { growth: 0.3, bloom: 0.2, roots: 0.35, mold: 0.9, bacteria: 0.6 },
      visualParameters: { density: 0.9, speed: 0.7, glitchAmount: 0.5, trailAmount: 0.1 },
      bridgeSensitivity: 0.9,
      bridgeSmoothing: 0.35,
    },
  },
  {
    id: 'jammer',
    name: 'Jammer',
    description: 'Grid pulse jamming — broken sub pulses and alarm-tone transients.',
    category: 'resistance',
    tags: ['signal-9', 'jammer', 'grid', 'resistance', 'mood:grid-resistance', 'accent:#ffcc00'],
    sound: { presetId: 'bacteria' },
    visual: { presetId: 'bacteria' },
    audioReactive: {
      enabled: true,
      sensitivity: 0.85,
      smoothing: 0.45,
      mappings: [
        { feature: 'bass', target: 'density', amount: 0.65, enabled: true },
        { feature: 'mids', target: 'motion', amount: 0.55, enabled: true },
        { feature: 'highs', target: 'brightness', amount: 0.45, enabled: true },
        { feature: 'amplitude', target: 'scale', amount: 0.5, enabled: true },
        { feature: 'transient', target: 'glitch', amount: 0.55, enabled: true },
      ],
    },
    workspace: { activeInspectorPanel: 'audio-reactive' },
    ui: {
      audioReactiveEnabled: true,
      tempo: 96,
      soundParameters: { growth: 0.4, bloom: 0.25, roots: 0.3, mold: 0.55, bacteria: 0.85 },
      visualParameters: { density: 0.75, speed: 0.65, glitchAmount: 0.3, trailAmount: 0.15 },
      bridgeSensitivity: 0.85,
      bridgeSmoothing: 0.45,
    },
  },
  {
    id: 'uplink',
    name: 'Uplink',
    description: 'Resistance uplink burst — tape-delay motion through the broadcast grid.',
    category: 'resistance',
    tags: ['signal-9', 'uplink', 'transmission', 'resistance', 'mood:encrypted-burst', 'accent:#a78bfa'],
    sound: { presetId: 'mutation' },
    visual: { presetId: 'mutation' },
    audioReactive: {
      enabled: true,
      sensitivity: 0.75,
      smoothing: 0.55,
      mappings: [
        { feature: 'bass', target: 'density', amount: 0.45, enabled: true },
        { feature: 'mids', target: 'motion', amount: 0.65, enabled: true },
        { feature: 'highs', target: 'brightness', amount: 0.55, enabled: true },
        { feature: 'amplitude', target: 'scale', amount: 0.45, enabled: true },
        { feature: 'transient', target: 'glitch', amount: 0.35, enabled: true },
      ],
    },
    workspace: { activeInspectorPanel: 'audio-reactive' },
    ui: {
      audioReactiveEnabled: true,
      tempo: 88,
      soundParameters: { growth: 0.45, bloom: 0.3, roots: 0.25, mold: 0.5, bacteria: 0.65 },
      visualParameters: { density: 0.7, speed: 0.55, glitchAmount: 0.22, trailAmount: 0.2 },
      bridgeSensitivity: 0.75,
      bridgeSmoothing: 0.55,
    },
  },
  {
    id: 'blackout',
    name: 'Blackout',
    description: 'Total grid collapse — encrypted silence before the next broadcast wave.',
    category: 'experimental',
    tags: ['signal-9', 'blackout', 'collapse', 'broadcast', 'mood:collapse', 'accent:#ff3355'],
    sound: { presetId: 'drone' },
    visual: { presetId: 'drone' },
    audioReactive: {
      enabled: true,
      sensitivity: 0.95,
      smoothing: 0.3,
      mappings: [
        { feature: 'bass', target: 'density', amount: 0.6, enabled: true },
        { feature: 'mids', target: 'motion', amount: 0.7, enabled: true },
        { feature: 'highs', target: 'brightness', amount: 0.4, enabled: true },
        { feature: 'amplitude', target: 'scale', amount: 0.4, enabled: true },
        { feature: 'transient', target: 'glitch', amount: 0.9, enabled: true },
      ],
    },
    workspace: { activeInspectorPanel: 'visual-parameters' },
    ui: {
      audioReactiveEnabled: true,
      tempo: 120,
      soundParameters: { growth: 0.35, bloom: 0.2, roots: 0.2, mold: 0.8, bacteria: 0.7 },
      visualParameters: { density: 0.95, speed: 0.75, glitchAmount: 0.6, trailAmount: 0.05 },
      bridgeSensitivity: 0.95,
      bridgeSmoothing: 0.3,
    },
  },
];

export const {{APP_CONST}}_STARTER_BUNDLE = {{APP_CONST}}_BROADCAST_BUNDLE;
