/**
 * Official prototype type catalog — defaults for layout, renderer, features,
 * components, panels, patterns, and roadmap per type.
 */
import type { PrototypeType, PrototypeTypeSpec } from './types.ts';

export const PROTOTYPE_TYPES: PrototypeTypeSpec[] = [
  {
    type: 'audio-reactive-installation',
    name: 'Audio Reactive Installation',
    purpose: 'Immersive installation driven by ambient or live audio with fullscreen visuals.',
    defaultLayout: 'layout.canvas',
    shellVariant: 'instrument',
    defaultRenderer: 'canvas',
    defaults: { sound: true, midi: false, touch: false, documentation: true },
    components: ['component.statusIndicator', 'component.iconButton', 'component.panel'],
    panels: [
      { id: 'audio', title: 'Audio Input', description: 'Source, gain, and analysis settings.' },
      { id: 'visual', title: 'Visual Response', description: 'Mapping audio features to visuals.' },
    ],
    patterns: ['pattern.transport'],
    roadmap: ['Wire audio analyser → visual parameters', 'Add asset upload for installation media', 'Performance mode for venue display'],
  },
  {
    type: 'generative-art',
    name: 'Generative Art',
    purpose: 'Algorithmic visuals with parameter exploration and export.',
    defaultLayout: 'layout.canvas',
    shellVariant: 'instrument',
    defaultRenderer: 'canvas',
    defaults: { sound: false, midi: false, touch: false, documentation: true },
    components: ['component.controlGroup', 'component.panel', 'component.button'],
    panels: [{ id: 'parameters', title: 'Parameters', description: 'Seed, palette, and generative controls.' }],
    patterns: ['pattern.inspector'],
    roadmap: ['Implement generative core in src/engines/visual.ts', 'Add preset save/recall', 'Export still / loop'],
  },
  {
    type: 'visual-synth',
    name: 'Visual Synth',
    purpose: 'Real-time visual synthesis with transport and modulation.',
    defaultLayout: 'layout.instrument',
    shellVariant: 'instrument',
    defaultRenderer: 'canvas',
    defaults: { sound: true, midi: true, touch: false, documentation: true },
    components: ['component.toolbar', 'component.iconButton', 'component.statusIndicator'],
    panels: [
      { id: 'oscillator', title: 'Oscillator', description: 'Visual oscillator / source controls.' },
      { id: 'modulation', title: 'Modulation', description: 'LFO and envelope mapping.' },
    ],
    patterns: ['pattern.transport', 'pattern.inspector'],
    roadmap: ['Connect transport to visual engine', 'MIDI learn for parameters', 'Add output metrics HUD'],
  },
  {
    type: 'music-instrument',
    name: 'Music Instrument',
    purpose: 'Playable instrument with transport, MIDI, and performance controls.',
    defaultLayout: 'layout.instrument',
    shellVariant: 'instrument',
    defaultRenderer: 'canvas',
    defaults: { sound: true, midi: true, touch: true, documentation: true },
    components: ['component.button', 'component.controlGroup', 'component.panel'],
    panels: [
      { id: 'voice', title: 'Voice', description: 'Timbre and voice parameters.' },
      { id: 'performance', title: 'Performance', description: 'Macros and performance controls.' },
    ],
    patterns: ['pattern.transport', 'pattern.inspector', 'pattern.timeline'],
    roadmap: ['Integrate sound engine adapter', 'MIDI input + learn', 'Touch performance mode'],
  },
  {
    type: 'ai-assistant',
    name: 'AI Assistant',
    purpose: 'Conversational assistant UI with command palette and settings.',
    defaultLayout: 'layout.dashboard',
    shellVariant: 'standard',
    defaultRenderer: 'html',
    defaults: { sound: false, midi: false, touch: false, documentation: true },
    components: ['component.card', 'component.section', 'component.button'],
    panels: [{ id: 'settings', title: 'Settings', description: 'Model and prompt configuration.' }],
    patterns: ['pattern.command-palette', 'pattern.search'],
    roadmap: ['Wire AI provider adapter in src/engines/ai.ts', 'Conversation history panel', 'Command palette actions'],
  },
  {
    type: 'interactive-object',
    name: 'Interactive Object',
    purpose: 'Physical or screen-based object with touch/gesture interaction.',
    defaultLayout: 'layout.instrument',
    shellVariant: 'instrument',
    defaultRenderer: 'canvas',
    defaults: { sound: false, midi: false, touch: true, documentation: true },
    components: ['component.surface', 'component.statusIndicator'],
    panels: [{ id: 'interaction', title: 'Interaction', description: 'Touch zones and gesture mapping.' }],
    patterns: ['pattern.inspector'],
    roadmap: ['Enable touch display mode', 'Map pointer/gesture input layer', 'Object state machine'],
  },
  {
    type: 'lighting-controller',
    name: 'Lighting Controller',
    purpose: 'DMX / fixture control with scenes and MIDI triggers.',
    defaultLayout: 'layout.studio',
    shellVariant: 'instrument',
    defaultRenderer: 'html',
    defaults: { sound: false, midi: true, touch: true, documentation: true },
    components: ['component.toolbar', 'component.controlGroup', 'component.badge'],
    panels: [
      { id: 'fixtures', title: 'Fixtures', description: 'Fixture list and addressing.' },
      { id: 'scenes', title: 'Scenes', description: 'Scene storage and recall.' },
    ],
    patterns: ['pattern.transport', 'pattern.workspace'],
    roadmap: ['Fixture patch placeholder', 'Scene bank UI', 'MIDI trigger mapping'],
  },
  {
    type: 'portfolio-demo',
    name: 'Portfolio Demo',
    purpose: 'Showcase work with documentation layout and media embeds.',
    defaultLayout: 'layout.landing',
    shellVariant: 'standard',
    defaultRenderer: 'html',
    defaults: { sound: false, midi: false, touch: false, documentation: true },
    components: ['component.card', 'component.section', 'primitive.grid'],
    panels: [],
    patterns: ['pattern.search'],
    roadmap: ['Hero + project grid', 'Case study pages', 'Deploy preview URL'],
  },
  {
    type: 'presentation-prototype',
    name: 'Presentation Prototype',
    purpose: 'Audience-facing demo with presentation mode and minimal chrome.',
    defaultLayout: 'layout.presentation',
    shellVariant: 'instrument',
    defaultRenderer: 'canvas',
    defaults: { sound: false, midi: false, touch: false, documentation: true },
    components: ['component.iconButton', 'component.statusIndicator'],
    panels: [{ id: 'notes', title: 'Presenter Notes', description: 'Hidden notes for the presenter.' }],
    patterns: ['pattern.command-palette'],
    roadmap: ['Presentation mode toggle', 'Branding overlay', 'Remote advance (optional)'],
  },
  {
    type: 'creative-tool',
    name: 'Creative Tool',
    purpose: 'Multi-panel authoring tool with browser, inspector, and timeline.',
    defaultLayout: 'layout.studio',
    shellVariant: 'instrument',
    defaultRenderer: 'canvas',
    defaults: { sound: false, midi: false, touch: false, documentation: true },
    components: ['component.panel', 'component.toolbar', 'component.card'],
    panels: [
      { id: 'library', title: 'Library', description: 'Assets and presets.' },
      { id: 'properties', title: 'Properties', description: 'Selection properties.' },
    ],
    patterns: ['pattern.asset-browser', 'pattern.inspector', 'pattern.timeline'],
    roadmap: ['Dockable panel layout', 'Asset browser stub', 'Timeline region stub'],
  },
  {
    type: 'data-visualization',
    name: 'Data Visualization',
    purpose: 'Dashboard for exploring datasets with charts and filters.',
    defaultLayout: 'layout.dashboard',
    shellVariant: 'standard',
    defaultRenderer: 'canvas',
    defaults: { sound: false, midi: false, touch: false, documentation: true },
    components: ['component.card', 'component.section', 'component.badge'],
    panels: [{ id: 'filters', title: 'Filters', description: 'Dataset filters and ranges.' }],
    patterns: ['pattern.search', 'pattern.settings'],
    roadmap: ['Load sample dataset', 'Chart canvas adapter', 'Export snapshot'],
  },
  {
    type: 'research-experiment',
    name: 'Research Experiment',
    purpose: 'Hypothesis-driven experiment with logging and reproducible runs.',
    defaultLayout: 'layout.workspace',
    shellVariant: 'standard',
    defaultRenderer: 'canvas',
    defaults: { sound: false, midi: false, touch: false, documentation: true },
    components: ['component.section', 'component.controlGroup', 'component.statusIndicator'],
    panels: [
      { id: 'hypothesis', title: 'Hypothesis', description: 'Experiment parameters and notes.' },
      { id: 'results', title: 'Results', description: 'Run output and metrics.' },
    ],
    patterns: ['pattern.inspector', 'pattern.workspace'],
    roadmap: ['Run log to console / file', 'Parameter sweep helper', 'Document methodology in README'],
  },
];

export const PROTOTYPE_TYPE_IDS = PROTOTYPE_TYPES.map((t) => t.type) as PrototypeType[];

export function getPrototypeTypeSpec(type: PrototypeType): PrototypeTypeSpec {
  const spec = PROTOTYPE_TYPES.find((t) => t.type === type);
  if (!spec) throw new Error(`Unknown prototype type: ${type}`);
  return spec;
}

export function isPrototypeType(id: string): id is PrototypeType {
  return PROTOTYPE_TYPE_IDS.includes(id as PrototypeType);
}
