import type { PresetBundle } from '@plantasonic/platform-types';

/** Flowers botanical preset bundles — audio-reactive visual instrument sessions */
export const {{APP_CONST}}_PRESET_BUNDLES: PresetBundle[] = [
  {
    id: 'stem',
    name: 'Stem',
    description: 'Upward growth — soft pulses drive vertical motion and density.',
    category: 'botanical',
    tags: ['flowers', 'stem', 'growth'],
    sound: { presetId: 'root' },
    visual: { presetId: 'root' },
    audioReactive: {
      enabled: true,
      sensitivity: 0.55,
      smoothing: 0.75,
      mappings: [
        { feature: 'bass', target: 'density', amount: 0.4, enabled: true },
        { feature: 'mids', target: 'motion', amount: 0.45, enabled: true },
        { feature: 'highs', target: 'brightness', amount: 0.2, enabled: true },
        { feature: 'amplitude', target: 'scale', amount: 0.35, enabled: true },
        { feature: 'transient', target: 'glitch', amount: 0.05, enabled: true },
      ],
    },
    workspace: { activeInspectorPanel: 'audio-reactive' },
    ui: {
      audioReactiveEnabled: true,
      tempo: 64,
      soundParameters: { growth: 0.55, bloom: 0.3, roots: 0.65, mold: 0.1, bacteria: 0.15 },
      visualParameters: { density: 0.55, speed: 0.35, glitchAmount: 0.02, trailAmount: 0.45 },
      bridgeSensitivity: 0.55,
      bridgeSmoothing: 0.75,
    },
  },
  {
    id: 'petal',
    name: 'Petal',
    description: 'Unfolding petals — harmonic bloom modulates brightness and scale.',
    category: 'botanical',
    tags: ['flowers', 'petal', 'soft'],
    sound: { presetId: 'bloom' },
    visual: { presetId: 'bloom' },
    audioReactive: {
      enabled: true,
      sensitivity: 0.6,
      smoothing: 0.7,
      mappings: [
        { feature: 'bass', target: 'density', amount: 0.3, enabled: true },
        { feature: 'mids', target: 'motion', amount: 0.5, enabled: true },
        { feature: 'highs', target: 'brightness', amount: 0.5, enabled: true },
        { feature: 'amplitude', target: 'scale', amount: 0.4, enabled: true },
        { feature: 'transient', target: 'glitch', amount: 0.08, enabled: true },
      ],
    },
    workspace: { activeInspectorPanel: 'visual-parameters' },
    ui: {
      audioReactiveEnabled: true,
      tempo: 72,
      soundParameters: { growth: 0.5, bloom: 0.75, roots: 0.35, mold: 0.1, bacteria: 0.2 },
      visualParameters: { density: 0.5, speed: 0.45, glitchAmount: 0.04, trailAmount: 0.35 },
      bridgeSensitivity: 0.6,
      bridgeSmoothing: 0.7,
    },
  },
  {
    id: 'bloom',
    name: 'Bloom',
    description: 'Full harmonic bloom — mids and highs grow sound into light.',
    category: 'botanical',
    tags: ['flowers', 'bloom', 'bright'],
    sound: { presetId: 'flowers' },
    visual: { presetId: 'flowers' },
    audioReactive: {
      enabled: true,
      sensitivity: 0.7,
      smoothing: 0.6,
      mappings: [
        { feature: 'bass', target: 'density', amount: 0.35, enabled: true },
        { feature: 'mids', target: 'motion', amount: 0.55, enabled: true },
        { feature: 'highs', target: 'brightness', amount: 0.55, enabled: true },
        { feature: 'amplitude', target: 'scale', amount: 0.45, enabled: true },
        { feature: 'transient', target: 'glitch', amount: 0.1, enabled: true },
      ],
    },
    workspace: { activeInspectorPanel: 'visual-parameters' },
    ui: {
      audioReactiveEnabled: true,
      tempo: 80,
      soundParameters: { growth: 0.6, bloom: 0.85, roots: 0.3, mold: 0.08, bacteria: 0.18 },
      visualParameters: { density: 0.6, speed: 0.5, glitchAmount: 0.06, trailAmount: 0.3 },
      bridgeSensitivity: 0.7,
      bridgeSmoothing: 0.6,
    },
  },
  {
    id: 'pollinate',
    name: 'Pollinate',
    description: 'Drifting pollination — ambient tones with trailing organic motion.',
    category: 'ambient',
    tags: ['flowers', 'pollinate', 'ambient'],
    sound: { presetId: 'moss' },
    visual: { presetId: 'moss' },
    audioReactive: {
      enabled: true,
      sensitivity: 0.45,
      smoothing: 0.85,
      mappings: [
        { feature: 'bass', target: 'density', amount: 0.25, enabled: true },
        { feature: 'mids', target: 'motion', amount: 0.35, enabled: true },
        { feature: 'highs', target: 'brightness', amount: 0.3, enabled: true },
        { feature: 'amplitude', target: 'scale', amount: 0.3, enabled: true },
        { feature: 'transient', target: 'glitch', amount: 0.04, enabled: true },
      ],
    },
    workspace: { activeInspectorPanel: 'audio-reactive' },
    ui: {
      audioReactiveEnabled: true,
      tempo: 56,
      soundParameters: { growth: 0.35, bloom: 0.4, roots: 0.45, mold: 0.12, bacteria: 0.25 },
      visualParameters: { density: 0.45, speed: 0.3, glitchAmount: 0.02, trailAmount: 0.55 },
      bridgeSensitivity: 0.45,
      bridgeSmoothing: 0.85,
    },
  },
];

export const {{APP_CONST}}_SEED_BUNDLE: PresetBundle = {
  id: 'seed',
  name: 'Seed',
  description: 'First sprout — gentle ambient tone seeds the botanical visual form.',
  category: 'botanical',
  tags: ['flowers', 'seed', 'starter'],
  sound: { presetId: 'seed' },
  visual: { presetId: 'seed' },
  audioReactive: {
    enabled: true,
    sensitivity: 0.5,
    smoothing: 0.8,
    mappings: [
      { feature: 'bass', target: 'density', amount: 0.3, enabled: true },
      { feature: 'mids', target: 'motion', amount: 0.35, enabled: true },
      { feature: 'highs', target: 'brightness', amount: 0.25, enabled: true },
      { feature: 'amplitude', target: 'scale', amount: 0.25, enabled: true },
      { feature: 'transient', target: 'glitch', amount: 0.04, enabled: true },
    ],
  },
  workspace: { activeInspectorPanel: 'audio-reactive' },
  ui: {
    audioReactiveEnabled: true,
    tempo: {{DEFAULT_TEMPO}},
    soundParameters: { growth: 0.4, bloom: 0.35, roots: 0.5, mold: 0.08, bacteria: 0.12 },
    visualParameters: { density: 0.5, speed: 0.35, glitchAmount: 0.03, trailAmount: 0.4 },
    bridgeSensitivity: 0.5,
    bridgeSmoothing: 0.8,
  },
};

export const {{APP_CONST}}_STARTER_BUNDLE = {{APP_CONST}}_SEED_BUNDLE;
