/**
 * Deployment framework — standardized targets and generated config.
 */
import type { DeploymentTarget, ProjectManifest } from './types.ts';

export interface DeploymentSpec {
  target: DeploymentTarget;
  name: string;
  description: string;
  /** Generated config filename. */
  configFile: string;
}

export const DEPLOYMENT_TARGETS: DeploymentSpec[] = [
  { target: 'local', name: 'Local Development', description: 'Vite dev server.', configFile: 'vite.config.ts' },
  { target: 'preview', name: 'Preview', description: 'Static preview build.', configFile: 'vercel.json' },
  { target: 'production', name: 'Production', description: 'Production static hosting.', configFile: 'vercel.json' },
  { target: 'desktop', name: 'Desktop', description: 'Electron wrapper (starter template).', configFile: 'electron/' },
  { target: 'mobile', name: 'Mobile', description: 'Responsive PWA with touch mode.', configFile: 'vercel.json' },
  { target: 'pwa', name: 'PWA', description: 'Installable progressive web app.', configFile: 'public/manifest.webmanifest' },
  { target: 'embedded', name: 'Embedded Installation', description: 'Kiosk / fullscreen embedded mode.', configFile: 'src/prototype-config.ts' },
];

export function getDeploymentTargets(): DeploymentSpec[] {
  return [...DEPLOYMENT_TARGETS];
}

export function generateVercelConfig(): string {
  return JSON.stringify(
    { buildCommand: 'npm run build', outputDirectory: 'dist', framework: 'vite' },
    null,
    2,
  ) + '\n';
}

export function generatePwaManifest(project: { name: string; description?: string }): string {
  return JSON.stringify(
    {
      name: project.name,
      short_name: project.name.slice(0, 12),
      description: project.description ?? `${project.name} — Plantasonic creative prototype`,
      start_url: '/',
      display: 'standalone',
      background_color: '#0a0a0a',
      theme_color: '#00ff57',
    },
    null,
    2,
  ) + '\n';
}

export function generateDeployDocs(manifest: ProjectManifest): string {
  return `# Deployment — ${manifest.name}

| Field | Value |
| --- | --- |
| Target | \`${manifest.deployment.target}\` |
| Status | \`${manifest.deployment.status}\` |
| URL | ${manifest.deployment.url ?? '_not deployed_'} |

## Commands

\`\`\`bash
npm run dev       # local (${manifest.deployment.target === 'local' ? 'active' : '—'})
npm run build     # production bundle
npm run preview   # local preview
\`\`\`

## Targets

${DEPLOYMENT_TARGETS.map((t) => `- **${t.name}** (\`${t.target}\`) — ${t.description}`).join('\n')}

Configuration is generated by the Platform SDK — do not hand-edit deployment infrastructure.
`;
}

/** Update manifest deployment status (e.g. after publish). */
export function markDeployed(
  manifest: ProjectManifest,
  status: ProjectManifest['deployment']['status'],
  url?: string,
): ProjectManifest {
  return {
    ...manifest,
    deployment: { ...manifest.deployment, status, url: url ?? manifest.deployment.url },
    updatedAt: new Date().toISOString(),
  };
}
