import type { ControlDef } from '../core/types';

export const motionControlDefs: ControlDef[] = [
  { name: 'density', label: 'Density', min: 0.3, max: 2, default: 1, step: 0.1 },
  { name: 'speed', label: 'Speed', min: 0.1, max: 3, default: 1, step: 0.1 },
  { name: 'strength', label: 'Strength', min: 0, max: 1, default: 0.7, step: 0.05 },
  { name: 'randomness', label: 'Randomness', min: 0, max: 1, default: 0.3, step: 0.05 },
  { name: 'frequency', label: 'Frequency', min: 0.1, max: 3, default: 1, step: 0.1 },
  { name: 'amplitude', label: 'Amplitude', min: 0, max: 2, default: 1, step: 0.05 },
  { name: 'decay', label: 'Decay', min: 0, max: 1, default: 0.1, step: 0.05 },
  { name: 'drag', label: 'Drag', min: 0, max: 1, default: 0.05, step: 0.05 },
  { name: 'gravity', label: 'Gravity', min: 0, max: 2, default: 0.5, step: 0.05 },
  { name: 'noiseScale', label: 'Noise Scale', min: 0.1, max: 3, default: 1, step: 0.1 },
  { name: 'flowStrength', label: 'Flow Strength', min: 0, max: 1, default: 0.8, step: 0.05 },
  { name: 'blendWeight', label: 'Blend Weight', min: 0, max: 1, default: 1, step: 0.05 },
  { name: 'trailAmount', label: 'Trails', min: 0, max: 1, default: 0.4, step: 0.05 },
  { name: 'glitchAmount', label: 'Glitch', min: 0, max: 1, default: 0.1, step: 0.05 },
  { name: 'symmetry', label: 'Symmetry', min: 2, max: 12, default: 6, step: 1 },
  { name: 'petals', label: 'Petals', min: 3, max: 12, default: 5, step: 1 },
  { name: 'spiralAmount', label: 'Spiral', min: 0, max: 1, default: 0.5, step: 0.05 },
  { name: 'cellularAmount', label: 'Cellular', min: 0, max: 1, default: 0.5, step: 0.05 },
  { name: 'scanlineAmount', label: 'Scanline', min: 0, max: 1, default: 0.5, step: 0.05 },
];

export const baseMotionDefaults = {
  density: 1,
  speed: 1,
  trailAmount: 0.4,
  glitchAmount: 0.1,
  strength: 0.7,
  randomness: 0.3,
  frequency: 1,
  amplitude: 1,
  decay: 0.1,
  drag: 0.05,
  gravity: 0.5,
  noiseScale: 1,
  flowStrength: 0.8,
  blendWeight: 1,
  symmetry: 6,
  petals: 5,
  spiralAmount: 0.5,
  cellularAmount: 0.5,
  scanlineAmount: 0.5,
};
