import type { AsciiPreset } from '../core/types';

export const organicPreset: AsciiPreset = {
  id: 'organic',
  name: 'Organic Classic',
  glyphSet: ['·', '°', '○', '●', '◦', '∘', '∙', '◉'],
  motionField: 'noise',
  plugins: [
    { id: 'noise', type: 'effect' },
    { id: 'burst', type: 'effect' },
    { id: 'trails', type: 'effect' },
    { id: 'radialSymmetry', type: 'pattern' },
    { id: 'cellular', type: 'pattern' },
  ],
  effects: [
    { type: 'noise', enabled: true },
    { type: 'burst', enabled: true },
    { type: 'glitch', enabled: false },
    { type: 'trails', enabled: true },
  ],
  patterns: ['radialSymmetry', 'cellular'],
  controls: [
    {
      name: 'density',
      label: 'Density',
      min: 0.3,
      max: 2,
      default: 0.9,
      step: 0.1,
    },
    {
      name: 'speed',
      label: 'Speed',
      min: 0.1,
      max: 3,
      default: 0.5,
      step: 0.1,
    },
    {
      name: 'trailAmount',
      label: 'Trails',
      min: 0,
      max: 1,
      default: 0.7,
      step: 0.05,
    },
    {
      name: 'glitchAmount',
      label: 'Glitch',
      min: 0,
      max: 1,
      default: 0,
      step: 0.05,
    },
    {
      name: 'symmetry',
      label: 'Symmetry',
      min: 2,
      max: 12,
      default: 8,
      step: 1,
    },
    {
      name: 'petals',
      label: 'Petals',
      min: 3,
      max: 12,
      default: 7,
      step: 1,
    },
    {
      name: 'spiralAmount',
      label: 'Spiral',
      min: 0,
      max: 1,
      default: 0.25,
      step: 0.05,
    },
    {
      name: 'cellularAmount',
      label: 'Cellular',
      min: 0,
      max: 1,
      default: 0.65,
      step: 0.05,
    },
    {
      name: 'scanlineAmount',
      label: 'Scanline',
      min: 0,
      max: 1,
      default: 0,
      step: 0.05,
    },
  ],
  density: 0.9,
  speed: 0.5,
  trailAmount: 0.7,
  glitchAmount: 0,
  symmetry: 8,
  petals: 7,
  spiralAmount: 0.25,
  cellularAmount: 0.65,
  scanlineAmount: 0,
};
